const test = require('node:test');
const assert = require('node:assert/strict');
const path = require('path');
const fs = require('fs');
const os = require('os');
const writeMIR = require('../onboarding/backend/write-mir.cjs');

test('Suite 5: Write-MIR Logic & Overrides', async (t) => {
  let tmpDir;
  let templateDir;
  let localDir;
  let profileTplPath = 'Core_Strategy/01_COMPANY/PROFILE.md';

  t.beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'markos-mir-test-'));
    templateDir = path.join(tmpDir, 'templates');
    localDir = path.join(tmpDir, 'local');

    // Setup baseline templates and state table.
    fs.mkdirSync(path.join(templateDir, 'Core_Strategy', '01_COMPANY'), { recursive: true });
    fs.writeFileSync(path.join(templateDir, profileTplPath), [
      '# Company Profile',
      '## Company Snapshot',
      'Original snapshot body',
      '## Positioning',
      'Original positioning body',
      '## Buyer Signals',
      'Original buyer-signals body'
    ].join('\n\n'));
    fs.writeFileSync(path.join(templateDir, 'STATE.md'), `Original STATE\n| \`${profileTplPath}\` | \`empty\` | — |`);
  });

  t.afterEach(() => {
    try { fs.rmSync(tmpDir, { recursive: true, force: true, maxRetries: 5 }); } catch(e) {}
  });

  await t.test('5.1 JIT cloning + expected header merge writes provenance and state', async () => {
    const drafts = {
      company_profile: [
        '## Company Snapshot',
        'Merged snapshot from approved draft.',
        '## Positioning',
        'Merged positioning statement.'
      ].join('\n\n')
    };

    const result = writeMIR.applyDrafts(localDir, templateDir, drafts);
    
    assert.deepEqual(result.written, [profileTplPath]);
    assert.equal(result.stateUpdated, true);
    assert.equal(result.errors.length, 0);
    assert.ok(result.mergeEvents.some((event) => event.type === 'header-replaced' && event.header === 'Company Snapshot'));
    
    // It should have created the local profile and merged section bodies.
    const localProfile = fs.readFileSync(path.join(localDir, profileTplPath), 'utf8');
    assert.match(localProfile, /Merged snapshot from approved draft\./);
    assert.match(localProfile, /Merged positioning statement\./);
    // NOTE: During the transition from the legacy "MARKOS" branding to "MarkOS",
    // we accept either label in the provenance line for backward compatibility.
    // TODO: Once all generators emit "MarkOS" consistently, tighten this regex
    // to only match "MarkOS" and remove support for "MARKOS".
    assert.match(localProfile, /Generated by (MarkOS|MARKOS) AI/);

    // It should have cloned STATE.md and marked it complete.
    const localState = fs.readFileSync(path.join(localDir, 'STATE.md'), 'utf8');
    assert.match(localState, /`complete`/);
  });

  await t.test('5.2 Header drift still merges by fuzzy match and keeps local state header', async () => {
    const driftedLocalTemplate = [
      '# Company Profile',
      '## Company Snapshot and POV',
      'Existing drifted body',
      '## Positioning',
      'Keep this section available'
    ].join('\n\n');

    fs.mkdirSync(path.join(localDir, 'Core_Strategy', '01_COMPANY'), { recursive: true });
    fs.writeFileSync(path.join(localDir, 'STATE.md'), `Pre-existing STATE\n| \`${profileTplPath}\` | \`complete\` | — |`);
    fs.writeFileSync(path.join(localDir, profileTplPath), driftedLocalTemplate);

    const drafts = {
      company_profile: [
        '## Company Snapshot',
        'Replacement body aligned via fuzzy header matching.'
      ].join('\n\n')
    };

    const result = writeMIR.applyDrafts(localDir, templateDir, drafts);

    assert.equal(result.written.length, 1);
    assert.ok(result.mergeEvents.some((event) => event.type === 'header-replaced' && event.header === 'Company Snapshot and POV'));
    
    // Content should be merged into the drifted header variant.
    const newProfile = fs.readFileSync(path.join(localDir, profileTplPath), 'utf8');
    assert.match(newProfile, /Replacement body aligned via fuzzy header matching\./);

    // Existing STATE header should remain preserved.
    const state = fs.readFileSync(path.join(localDir, 'STATE.md'), 'utf8');
    assert.match(state, /Pre-existing STATE/);
  });

  await t.test('5.3 Missing header path appends explicit fallback section', async () => {
    fs.mkdirSync(path.join(localDir, 'Core_Strategy', '01_COMPANY'), { recursive: true });
    fs.writeFileSync(path.join(localDir, profileTplPath), [
      '# Company Profile',
      '## Existing Header',
      'Stable content'
    ].join('\n\n'));

    const drafts = {
      company_profile: [
        '## Differentiation Matrix',
        'Fallback append should preserve approved content.'
      ].join('\n\n')
    };

    const result = writeMIR.applyDrafts(localDir, templateDir, drafts);
    assert.ok(result.mergeEvents.some((event) => event.type === 'header-fallback-append' && event.header === 'Differentiation Matrix'));

    const newProfile = fs.readFileSync(path.join(localDir, profileTplPath), 'utf8');
    assert.match(newProfile, /## Differentiation Matrix/);
    assert.match(newProfile, /Fallback append should preserve approved content\./);
  });

  await t.test('5.4 Multi-section drafts replace matched sections and append only unmatched ones', async () => {
    fs.mkdirSync(path.join(localDir, 'Core_Strategy', '01_COMPANY'), { recursive: true });
    fs.writeFileSync(path.join(localDir, profileTplPath), fs.readFileSync(path.join(templateDir, profileTplPath), 'utf8'));

    const drafts = {
      company_profile: [
        '## Company Snapshot',
        'Updated snapshot body.',
        '## Buyer Signals',
        'Updated buyer signals body.',
        '## Fresh Section',
        'This section must append because no template header exists.'
      ].join('\n\n')
    };

    const result = writeMIR.applyDrafts(localDir, templateDir, drafts);
    const profile = fs.readFileSync(path.join(localDir, profileTplPath), 'utf8');

    assert.match(profile, /Updated snapshot body\./);
    assert.match(profile, /Updated buyer signals body\./);
    assert.match(profile, /## Fresh Section/);
    assert.equal(result.mergeEvents.filter((event) => event.type === 'header-replaced').length >= 2, true);
    assert.ok(result.mergeEvents.some((event) => event.type === 'header-fallback-append' && event.header === 'Fresh Section'));
  });

  await t.test('5.5 Raw draft fallback append and state updates remain explicit', async () => {
    fs.mkdirSync(path.join(localDir, 'Core_Strategy', '01_COMPANY'), { recursive: true });
    fs.writeFileSync(path.join(localDir, profileTplPath), '# Company Profile\n\n## Existing\n\nBase text');

    const result = writeMIR.applyDrafts(localDir, templateDir, {
      company_profile: 'No markdown headings in this generated draft.'
    });

    const profile = fs.readFileSync(path.join(localDir, profileTplPath), 'utf8');
    assert.match(profile, /Fallback Draft Insert/);
    assert.ok(result.mergeEvents.some((event) => event.type === 'raw-fallback-append'));

    const localState = fs.readFileSync(path.join(localDir, 'STATE.md'), 'utf8');
    assert.match(localState, /`complete`/);
  });
});
