'use strict';

// Phase 202 Plan 04 D-13 + D-14: Strict AJV validator registry for MCP tool input + output schemas.
// - Single shared Ajv instance (strict mode + no coercion + no removeAdditional + no defaults).
// - ajv-formats enables date-time / email / uri / uuid.
// - Schemas keyed by tool_id; validators cached after compile.
// - Lazy-loads Plan 202-07's `_generated/tool-schemas.json` with fallback to empty registry.

const Ajv = require('ajv');
const addFormats = require('ajv-formats');

const STRICT_OPTS = Object.freeze({
  strict: true,
  strictSchema: true,
  strictTypes: true,
  allErrors: false,
  useDefaults: false,
  removeAdditional: false,
  coerceTypes: false,
});

// Ajv v8 ships as both a class (CJS default) and { default: class } (ESM interop).
const AjvCtor = Ajv.default || Ajv;
const ajv = new AjvCtor(STRICT_OPTS);
(addFormats.default || addFormats)(ajv);

const compiled = new Map();

function _loadGeneratedSchemas() {
  try {
    // Generated by Plan 202-07 scripts/openapi/build-mcp-schemas.mjs.
    // Absent at Plan 202-04 execution time — fallback keeps the module loadable.
    return require('./_generated/tool-schemas.json');
  } catch {
    return {};
  }
}

function compileToolSchemas(schemasByTool) {
  compiled.clear();
  for (const [tool_id, schemas] of Object.entries(schemasByTool || {})) {
    const inputKey = `${tool_id}.input`;
    const outputKey = `${tool_id}.output`;
    ajv.removeSchema(inputKey);
    ajv.removeSchema(outputKey);
    ajv.addSchema({ ...schemas.input, $id: inputKey }, inputKey);
    ajv.addSchema({ ...schemas.output, $id: outputKey }, outputKey);
    compiled.set(tool_id, {
      validateInput: ajv.getSchema(inputKey),
      validateOutput: ajv.getSchema(outputKey),
    });
  }
}

function getToolValidator(tool_id) {
  const v = compiled.get(tool_id);
  if (!v) throw new Error(`no_validator:${tool_id}`);
  return v;
}

// Boot-time registration from generated JSON (no-op when absent).
compileToolSchemas(_loadGeneratedSchemas());

module.exports = {
  ajv,
  STRICT_OPTS,
  compileToolSchemas,
  getToolValidator,
};
