import createClient from 'openapi-fetch';
// import type { paths } from './schema';
// NOTE: schema.d.ts is generated by `npm run generate` which runs
// scripts/sdk/prepare-openapi.cjs + openapi-typescript. Full generation
// is gated on hardening the scripts/openapi/build-openapi.cjs YAML subset
// parser (tracked as 200-01.1). Until then, the client exposes a loose
// `paths` type for forward-compat.

export type LoosePaths = Record<string, Record<string, unknown>>;

export type MarkosClientOptions = {
  baseUrl: string;
  fetch?: typeof fetch;
  headers?: Record<string, string>;
};

export function createMarkosClient<Paths extends LoosePaths = LoosePaths>(options: MarkosClientOptions) {
  return createClient<Paths>({
    baseUrl: options.baseUrl,
    fetch: options.fetch,
    headers: options.headers,
  });
}

export default createMarkosClient;
