#!/usr/bin/env node
/**
 * write-mir.cjs — MIR/MSP File Persistence & STATE.md Stamping
 * ═══════════════════════════════════════════════════════════════════════════════
 * PURPOSE:
 *   Writes approved AI drafts into the persistent `.markos-local/` directory.
 *   Ensures that base templates are NEVER modified, preserving the upgrade path.
 *
 * KEY BEHAVIORS:
 *   1. JIT-Cloning: If `.markos-local/MIR/` is missing, copies the entire template
 *      structure from `.agent/.../templates/MIR/` before writing.
 *   2. Fuzzy Merging: Uses a multi-step regex approach to inject draft content
 *      into specific `<!-- SECTION: ... -->` blocks within markdown files.
 *   3. STATE.md Stamping: After a successful file write, scans `STATE.md` and
 *      updates the corresponding row from `(empty)` to `(complete)`.
 *
 * FILE MAPPING (SECTION_FILE_MAP):
 *   Maps internal draft keys (e.g., 'company_profile') to relative file paths.
 *   This mapping is the source of truth for where drafts are persisted.
 *
 * EXPORTS:
 *   applyDrafts(slug, drafts, mirPath) → Promise<void>
 *
 * RELATED FILES:
 *   onboarding/backend/server.cjs          (caller — POST /approve handler)
 *   .agent/.../templates/MIR/              (source of base templates)
 *   .markos-local/MIR/                       (persistent client data - gitignored)
 *   .planning/STATE.md                     (phase completion tracker)
 * ═══════════════════════════════════════════════════════════════════════════════
 */
'use strict';

const fs   = require('fs');
const path = require('path');
const { appendRegenerationRecord } = require('./mir-lineage.cjs');

// ── Section → MIR/MSP File Mapping ───────────────────────────────────────────
// These paths are relative to the project root or the provided LOCAL_MIR_PATH.
// Note: channel_strategy points to a different top-level directory (MSP).
// Maps draft section keys → relative paths within the MIR directory
const SECTION_FILE_MAP = {
  company_profile:  'Core_Strategy/01_COMPANY/PROFILE.md',
  mission_values:   'Core_Strategy/01_COMPANY/MISSION-VISION-VALUES.md',
  audience:         'Market_Audiences/03_MARKET/AUDIENCES.md',
  competitive:      'Market_Audiences/03_MARKET/COMPETITIVE-LANDSCAPE.md',
  brand_voice:      'Core_Strategy/02_BRAND/VOICE-TONE.md',
  channel_strategy: '../MSP/Strategy/00_MASTER-PLAN/CHANNEL-STRATEGY.md',
};

// Maps section key → STATE.md file column to update from empty → complete
const STATE_ROW_PATTERNS = {
  company_profile:  'Core_Strategy/01_COMPANY/PROFILE.md',
  mission_values:   'Core_Strategy/01_COMPANY/MISSION-VISION-VALUES.md',
  audience:         'Market_Audiences/03_MARKET/AUDIENCES.md',
  competitive:      'Market_Audiences/03_MARKET/COMPETITIVE-LANDSCAPE.md',
  brand_voice:      'Core_Strategy/02_BRAND/VOICE-TONE.md',
};

/**
 * Write approved drafts into MIR template files.
 *
 * @param {string} mirPath  — absolute path to the .markos-local/MIR directory
 * @param {string} baseMirPath — absolute path to the .agent/.../templates/MIR directory
 * @param {object} approvedDrafts — { section_key: "markdown content", ... }
 * @returns {object} { written: string[], errors: string[] }
 */
function writeDrafts(mirPath, baseMirPath, approvedDrafts) {
  const written = [];
  const errors  = [];
  const mergeEvents = [];

  for (const [section, content] of Object.entries(approvedDrafts)) {
    const relPath = SECTION_FILE_MAP[section];
    if (!relPath) {
      errors.push(`Unknown section key: ${section}`);
      continue;
    }

    const filePath = path.join(mirPath, relPath);
    const baseFilePath = path.join(baseMirPath, relPath);
    const dir = path.dirname(filePath);

    try {
      // Ensure local directory exists
      fs.mkdirSync(dir, { recursive: true });

      const today = new Date().toISOString().split('T')[0];
      const disclaimer = `\n> 🤖 **Generated by MARKOS AI** on \`${today}\`\n<!-- status: complete -->\n<!-- source: onboarding-agent -->\n`;

      // JIT Target Discovery: read from local override first, fallback to pristine base
      let existingText = '';
      if (fs.existsSync(filePath)) {
        existingText = fs.readFileSync(filePath, 'utf8');
      } else if (fs.existsSync(baseFilePath)) {
        existingText = fs.readFileSync(baseFilePath, 'utf8');
      }

      if (existingText) {
        // Smart Merge: Swap sections by Header
        
        const normalize = str => str.toLowerCase().replace(/[^a-z]/g, '');

        // Parse incoming drafted sections by matching `## [Header Title]`
        const draftParts = content.split(/^##\s+/m);
        
        if (draftParts.length === 1) {
          // LLM generated no valid standard headers. Prevent data loss by appending the raw text.
          existingText += `\n\n> ⚠️ **Fallback Draft Insert**:\n\n${content}\n`;
          mergeEvents.push({ file: relPath, type: 'raw-fallback-append' });
        } else {
          for (let i = 1; i < draftParts.length; i++) {
          const firstLineBreak = draftParts[i].indexOf('\n');
          if (firstLineBreak === -1) continue;
          
          const headerTitle = draftParts[i].substring(0, firstLineBreak).trim();
          const draftBody = draftParts[i].substring(firstLineBreak).trim();
          const nHeaderTitle = normalize(headerTitle);
          
          // Find this header in the existing template and swap the body
          let matched = false;
          const templateParts = existingText.split(/^##\s+/m);
          for (let j = 1; j < templateParts.length; j++) {
            const tFirstLineBreak = templateParts[j].indexOf('\n');
            if (tFirstLineBreak === -1) continue;
            
            const tHeaderTitle = templateParts[j].substring(0, tFirstLineBreak).trim();
            const nTHeaderTitle = normalize(tHeaderTitle);
            
            // Match if either pure-alpha string contains the other
            const isMatch = (nHeaderTitle.includes(nTHeaderTitle) || nTHeaderTitle.includes(nHeaderTitle)) && nTHeaderTitle.length > 5;
            
            if (isMatch) {
               // We found a match in the template! Replace the body.
               templateParts[j] = `${tHeaderTitle}\n\n${draftBody}\n\n`;
               existingText = templateParts[0] + '## ' + templateParts.slice(1).join('## ');
               matched = true;
              mergeEvents.push({ file: relPath, type: 'header-replaced', header: tHeaderTitle });
               break; // move to next draft section
            }
          }
          
          // Fallback: append at bottom if the template didn't have a matching header
          if (!matched) {
             existingText += `\n\n## ${headerTitle}\n\n${draftBody}\n`;
             mergeEvents.push({ file: relPath, type: 'header-fallback-append', header: headerTitle });
          }
        }
        }
        
        // Ensure disclaimer exists near the top
        if (!existingText.includes('Generated by MARKOS AI')) {
           existingText = existingText.replace(/^(# .*?\n(?:<!--.*?-->\n)?)/, `$1${disclaimer}`);
        }
        
        fs.writeFileSync(filePath, existingText, 'utf8');
      } else {
        // Fallback: file does not exist, write bare draft
        const header = `<!-- markos-generated: ${new Date().toISOString()} -->\n<!-- status: complete -->\n<!-- source: onboarding-agent -->\n> 🤖 **Generated by MARKOS AI** on \`${today}\`\n\n`;
        fs.writeFileSync(filePath, header + content, 'utf8');
        mergeEvents.push({ file: relPath, type: 'new-file-write' });
      }
      
      written.push(relPath);
    } catch (err) {
      errors.push(`Failed to write ${relPath}: ${err.message}`);
    }
  }

  return { written, errors, mergeEvents };
}

/**
 * Update STATE.md rows matching written files from "empty" → "complete"
 *
 * @param {string} statePath  — absolute path to .markos-local/MIR/STATE.md
 * @param {string} baseStatePath — absolute path to .agent/.../templates/MIR/STATE.md
 * @param {string[]} writtenFiles — list of relative file paths that were written
 */
function updateStateFile(statePath, baseStatePath, writtenFiles) {
  if (!fs.existsSync(statePath)) {
    if (fs.existsSync(baseStatePath)) {
      // Clone pristine STATE.md to local override before editing
      fs.mkdirSync(path.dirname(statePath), { recursive: true });
      fs.copyFileSync(baseStatePath, statePath);
    } else {
      return;
    }
  }

  let content = fs.readFileSync(statePath, 'utf8');
  const today = new Date().toISOString().split('T')[0];

  for (const relPath of writtenFiles) {
    // Match table rows containing this file path and "empty" status
    // Row format: | `path/to/FILE.md` | `empty` | — |  Notes |
    const escapedPath = relPath.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const pattern = new RegExp(
      `(\\|\\s*\`${escapedPath}\`\\s*\\|\\s*)\`empty\`(\\s*\\|\\s*)—(\\s*\\|)`,
      'g'
    );
    content = content.replace(
      pattern,
      `$1\`complete\`$2${today}$3`
    );
  }

  fs.writeFileSync(statePath, content, 'utf8');
}

/**
 * Main entry point: write drafts + update state
 *
 * @param {string} mirPath       — absolute path to local MIR directory
 * @param {string} baseMirPath   — absolute path to base templates MIR directory
 * @param {object} approvedDrafts — { section_key: "content" }
 * @returns {object} { written, stateUpdated, errors }
 */
function applyCriticalEdit({
  tenantId,
  projectSlug,
  entityKey,
  rationale,
  parentVersionId,
  dependencyImpact,
  contentSnapshot,
  persistence,
  runId,
  effectiveAt,
  actorId,
}) {
  return appendRegenerationRecord({
    tenantId,
    projectSlug,
    entityKey,
    parentVersionId,
    rationale,
    dependencyImpact,
    contentSnapshot,
    persistence,
    runId,
    effectiveAt,
    actorId,
  });
}

function applyDrafts(mirPath, baseMirPath, approvedDrafts, options = {}) {
  const { written, errors, mergeEvents } = writeDrafts(mirPath, baseMirPath, approvedDrafts);

  const statePath = path.join(mirPath, 'STATE.md');
  const baseStatePath = path.join(baseMirPath, 'STATE.md');
  let stateUpdated = false;

  try {
    updateStateFile(statePath, baseStatePath, written);
    stateUpdated = true;
  } catch (err) {
    errors.push(`STATE.md update failed: ${err.message}`);
  }

  let regenerationRecord = null;
  if (options && options.criticalEdit) {
    regenerationRecord = applyCriticalEdit({
      tenantId: options.criticalEdit.tenantId,
      projectSlug: options.criticalEdit.projectSlug,
      entityKey: options.criticalEdit.entityKey,
      rationale: options.criticalEdit.rationale,
      parentVersionId: options.criticalEdit.parentVersionId,
      dependencyImpact: options.criticalEdit.dependencyImpact,
      contentSnapshot: options.criticalEdit.contentSnapshot || approvedDrafts,
      persistence: options.persistence,
      runId: options.criticalEdit.runId,
      effectiveAt: options.criticalEdit.effectiveAt,
      actorId: options.criticalEdit.actorId,
    });
  }

  return { written, stateUpdated, errors, mergeEvents, regenerationRecord };
}

module.exports = { applyCriticalEdit, applyDrafts, writeDrafts, updateStateFile };
