-- Phase 37: MarkOS UI Control Plane baseline schema
-- This migration assumes auth and workspace claims are configured upstream.

create table if not exists markos_workspaces (
  id text primary key,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists markos_company (
  id text primary key,
  workspace_id text not null references markos_workspaces(id) on delete cascade,
  name text not null,
  website text,
  description text not null,
  publish_state text not null default 'draft',
  schema_version text not null default '1.0.0',
  updated_by text not null,
  updated_at timestamptz not null default now()
);

create table if not exists markos_mir_documents (
  id text primary key,
  workspace_id text not null references markos_workspaces(id) on delete cascade,
  section text not null,
  content text not null,
  publish_state text not null default 'draft',
  schema_version text not null default '1.0.0',
  updated_by text not null,
  updated_at timestamptz not null default now()
);

create table if not exists markos_msp_plans (
  id text primary key,
  workspace_id text not null references markos_workspaces(id) on delete cascade,
  channel text not null,
  objective text not null,
  kpi_target text not null,
  publish_state text not null default 'draft',
  schema_version text not null default '1.0.0',
  updated_by text not null,
  updated_at timestamptz not null default now()
);

create table if not exists markos_icps (
  id text primary key,
  workspace_id text not null references markos_workspaces(id) on delete cascade,
  title text not null,
  pains jsonb not null default '[]'::jsonb,
  jobs_to_be_done jsonb not null default '[]'::jsonb,
  publish_state text not null default 'draft',
  schema_version text not null default '1.0.0',
  updated_by text not null,
  updated_at timestamptz not null default now()
);

create table if not exists markos_segments (
  id text primary key,
  workspace_id text not null references markos_workspaces(id) on delete cascade,
  name text not null,
  criteria jsonb not null default '[]'::jsonb,
  publish_state text not null default 'draft',
  schema_version text not null default '1.0.0',
  updated_by text not null,
  updated_at timestamptz not null default now()
);

create table if not exists markos_campaigns (
  id text primary key,
  workspace_id text not null references markos_workspaces(id) on delete cascade,
  name text not null,
  status text not null default 'planned',
  kpi_name text not null,
  kpi_target text not null,
  publish_state text not null default 'draft',
  schema_version text not null default '1.0.0',
  updated_by text not null,
  updated_at timestamptz not null default now()
);

create table if not exists markos_revisions (
  id bigint generated by default as identity primary key,
  workspace_id text not null references markos_workspaces(id) on delete cascade,
  entity_type text not null,
  entity_id text not null,
  revision_number integer not null,
  payload jsonb not null,
  created_by text not null,
  created_at timestamptz not null default now(),
  unique(workspace_id, entity_type, entity_id, revision_number)
);

create table if not exists markos_audit_log (
  id bigint generated by default as identity primary key,
  workspace_id text not null references markos_workspaces(id) on delete cascade,
  actor text not null,
  action text not null,
  entity_type text not null,
  entity_id text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table markos_workspaces enable row level security;
alter table markos_company enable row level security;
alter table markos_mir_documents enable row level security;
alter table markos_msp_plans enable row level security;
alter table markos_icps enable row level security;
alter table markos_segments enable row level security;
alter table markos_campaigns enable row level security;
alter table markos_revisions enable row level security;
alter table markos_audit_log enable row level security;

-- Workspace-scope policies. Requires request.jwt.claim.workspace_id to be set by auth middleware.
create policy if not exists markos_workspaces_same_workspace on markos_workspaces
  using (id = auth.jwt()->>'workspace_id');

create policy if not exists markos_company_same_workspace on markos_company
  using (workspace_id = auth.jwt()->>'workspace_id');

create policy if not exists markos_mir_same_workspace on markos_mir_documents
  using (workspace_id = auth.jwt()->>'workspace_id');

create policy if not exists markos_msp_same_workspace on markos_msp_plans
  using (workspace_id = auth.jwt()->>'workspace_id');

create policy if not exists markos_icps_same_workspace on markos_icps
  using (workspace_id = auth.jwt()->>'workspace_id');

create policy if not exists markos_segments_same_workspace on markos_segments
  using (workspace_id = auth.jwt()->>'workspace_id');

create policy if not exists markos_campaigns_same_workspace on markos_campaigns
  using (workspace_id = auth.jwt()->>'workspace_id');

create policy if not exists markos_revisions_same_workspace on markos_revisions
  using (workspace_id = auth.jwt()->>'workspace_id');

create policy if not exists markos_audit_same_workspace on markos_audit_log
  using (workspace_id = auth.jwt()->>'workspace_id');
