-- Phase 47: Multi-Provider LLM BYOK foundation
-- Workspace-scoped operator key storage, preferences, and call event ledger.

create table if not exists markos_operator_llm_preferences (
  id bigint generated by default as identity primary key,
  workspace_id text not null references markos_workspaces(id) on delete cascade,
  operator_id text not null,
  available_providers text[] not null default array['anthropic', 'openai', 'gemini'],
  primary_provider text not null default 'anthropic'
    check (primary_provider in ('anthropic', 'openai', 'gemini')),
  cost_budget_monthly_usd numeric(10, 2) not null default 100.00,
  allow_fallback boolean not null default true,
  fallback_template text not null default 'cost_optimized'
    check (fallback_template in ('cost_optimized', 'speed_optimized', 'reliability_optimized')),
  updated_by text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(workspace_id, operator_id)
);

create table if not exists markos_operator_api_keys (
  id bigint generated by default as identity primary key,
  workspace_id text not null references markos_workspaces(id) on delete cascade,
  operator_id text not null,
  provider text not null check (provider in ('anthropic', 'openai', 'gemini')),
  encrypted_key text not null,
  key_hash text not null,
  updated_by text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(workspace_id, operator_id, provider)
);

create index if not exists idx_markos_operator_api_keys_workspace_operator
  on markos_operator_api_keys(workspace_id, operator_id);

create table if not exists markos_llm_call_events (
  id bigint generated by default as identity primary key,
  workspace_id text not null references markos_workspaces(id) on delete cascade,
  operator_id text not null,
  provider text not null check (provider in ('anthropic', 'openai', 'gemini')),
  model text not null,
  input_tokens integer not null default 0,
  output_tokens integer not null default 0,
  estimated_cost_usd numeric(12, 6) not null default 0,
  decision_mode text not null default 'default'
    check (decision_mode in ('explicit', 'default', 'fallback')),
  fallback_attempts integer not null default 0,
  latency_ms integer,
  context jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_markos_llm_call_events_workspace_operator_created
  on markos_llm_call_events(workspace_id, operator_id, created_at desc);

alter table markos_operator_llm_preferences enable row level security;
alter table markos_operator_api_keys enable row level security;
alter table markos_llm_call_events enable row level security;

create policy if not exists markos_operator_llm_preferences_same_workspace on markos_operator_llm_preferences
  using (workspace_id = auth.jwt()->>'workspace_id');

create policy if not exists markos_operator_api_keys_same_workspace on markos_operator_api_keys
  using (workspace_id = auth.jwt()->>'workspace_id');

create policy if not exists markos_llm_call_events_same_workspace on markos_llm_call_events
  using (workspace_id = auth.jwt()->>'workspace_id');